from fpdf import FPDF
import models

def clean_text(text: str):
    """Encodes to latin-1 and replaces non-latin1 characters with '?' to prevent FPDF crashes."""
    if not text:
        return ""
    # Ensure it's a string
    text_str = str(text)
    # FPDF standard fonts (Helvetica) only support latin-1.
    return text_str.encode('latin-1', 'replace').decode('latin-1')

def generate_resume_pdf(user: models.User):
    # Higher quality configuration
    pdf = FPDF(orientation='P', unit='mm', format='A4')
    pdf.set_auto_page_break(auto=True, margin=15)
    pdf.add_page()
    
    # --- HEADER ---
    pdf.set_font("Helvetica", style="B", size=28)
    pdf.set_text_color(0, 0, 0) # Black for maximum compatibility
    pdf.cell(0, 15, clean_text(user.full_name.upper()), ln=1, align="C")
    
    pdf.set_font("Helvetica", style="", size=12)
    pdf.set_text_color(80, 80, 80)
    pdf.cell(0, 10, f"Contact: {clean_text(user.email)}", ln=1, align="C")
    
    pdf.ln(5)
    pdf.set_draw_color(0, 0, 0)
    pdf.set_line_width(0.5)
    pdf.line(20, pdf.get_y(), 190, pdf.get_y())
    pdf.ln(10)
    
    # --- SUMMARY ---
    if user.bio:
        pdf.set_font("Helvetica", style="B", size=16)
        pdf.set_text_color(0, 0, 0)
        pdf.cell(0, 10, "PROFESSIONAL SUMMARY", ln=1)
        pdf.set_font("Helvetica", size=12)
        pdf.set_text_color(0, 0, 0)
        pdf.multi_cell(0, 7, clean_text(user.bio))
        pdf.ln(8)
    
    # --- SKILLS ---
    if user.skills:
        pdf.set_font("Helvetica", style="B", size=16)
        pdf.set_text_color(0, 0, 0)
        pdf.cell(0, 10, "TECHNICAL SKILLS", ln=1)
        pdf.set_font("Helvetica", size=12)
        pdf.set_text_color(0, 0, 0)
        skills_text = ", ".join([f"{s.name}" for s in user.skills])
        pdf.multi_cell(0, 7, clean_text(skills_text))
        pdf.ln(8)
        
    # --- PROJECTS ---
    if user.projects:
        pdf.set_font("Helvetica", style="B", size=16)
        pdf.set_text_color(0, 0, 0)
        pdf.cell(0, 10, "EXPERIENCE & PROJECTS", ln=1)
        pdf.ln(2)
        
        for project in user.projects:
            # Title
            pdf.set_font("Helvetica", style="B", size=14)
            pdf.set_text_color(0, 0, 0)
            pdf.cell(0, 10, clean_text(project.title), ln=1)
            
            # Technologies
            if project.tech_stack:
                pdf.set_font("Helvetica", style="I", size=10)
                pdf.set_text_color(100, 100, 100)
                techs = ", ".join(project.tech_stack) if isinstance(project.tech_stack, list) else str(project.tech_stack)
                pdf.cell(0, 6, f"Stack: {clean_text(techs)}", ln=1)
                
            # Description
            pdf.set_font("Helvetica", size=12)
            pdf.set_text_color(0, 0, 0)
            pdf.multi_cell(0, 7, clean_text(project.description))
            pdf.ln(6)
            
    # Final check on Y
    if pdf.get_y() > 250:
        pdf.add_page()

    # --- FOOTER ---
    pdf.set_y(-15)
    pdf.set_font("Helvetica", style="I", size=8)
    pdf.set_text_color(150, 150, 150)
    pdf.cell(0, 10, "This document was generated by an AI Portfolio Intelligence Agent.", align="C")
    
    # Output binary
    return bytes(pdf.output())
